### ISSUE TITLE
One problem with Chinese translation and some other questions

### ISSUE THREAD

**Issue by QMike0** [jaar23/nb-assistant#1]
Hello, thank you for developing this plugin! 

there is one tiny problem with Chinese translation. As is shown in the following picture, `clear` should be translated into `清除` instead of `清楚` 
![image](https://github.com/jaar23/nb-assistant/assets/43239563/dc793a44-4f15-4599-af7d-1c1c9107698b)

Besides, I couldn't find the API configuration entry for LLM in the plugin settings, so I'm curious about how the plugin currently provides chat service? And will it support API configuration or use local LLM in the future?

**Comment by jaar23** [comment]
Hi, thanks for using this plugin.
My bad, for not double check on diff lang. Will update it tonight.
For setting up the API and token, you can leverage on the default AI settings to do it. This plugin will read from SiYuan default AI settings parameters.
As it aim to enhance the AI experience for SiYuan, I'm not maintaining a different set of API settings.
For supporting local llama, the current AI setting already supported it. You just have to run local llama or llama file with OpenAI API compatible format. Example, http://localhost:8080/v1.

**Comment by jaar23** [comment]
To configure AI setting for llamafile (https://github.com/Mozilla-Ocho/llamafile), which similar to local llama but easier to deploy. Download the model llamafile, then start it following the instructions from the github repository.

Use the following parameters in SiYuan AI settings.

```
API provider: OpenAI
Timeout: 120 (since local inferencing is slow) 
Model: LLaMA_CPP
API Key: no-key
API Base Url: http://localhost:8080/v1
```
You will be able to connect to the local LLM.

**Comment by QMike0** [comment]
> For setting up the API and token, you can leverage on the default AI settings to do it. This plugin will read from SiYuan default AI settings parameters.
As it aim to enhance the AI experience for SiYuan, I'm not maintaining a different set of API settings.

Thank you for your explanation, it might be better to show this information in the README file, for some of similar Siyuan plugins need to configure APIs in their own settings （not  SiYuan default AI settings parameters), people might feel confused about this difference.

**Comment by jaar23** [comment]
Updated the correct translation to 清除 and Readme.
I'll close this issue.
