### ISSUE TITLE
0.1.1版本使用deepseek无输出

### ISSUE THREAD

**Issue by 5kyfkr** [jaar23/nb-assistant#2]
如图，使用deepseek时无输出返回
![image](https://github.com/jaar23/nb-assistant/assets/63196026/f25db45b-ff79-481d-baa3-aae13d1c9026)
![image](https://github.com/jaar23/nb-assistant/assets/63196026/b3b4b152-13af-49b7-a735-cb86b80d9497)

**Comment by jaar23** [comment]
你好，我试了同样的对话， 都有回复。
<img width="688" alt="test" src="https://github.com/jaar23/nb-assistant/assets/123139486/2dd9c504-a200-4301-9397-3763bd79a726">
我发现你的问题是在AI 配置的最大token数那里。
<img width="1277" alt="setting" src="https://github.com/jaar23/nb-assistant/assets/123139486/17de0fb1-3036-4499-aa77-180212e8e368">
如果你设置为`0`， 那样将没有token让deepseek 生成任何东西。你可以试一下修改它。 2048 为大的数值，如果不想它说那么多话，给一个500也够了。
还有auto tag的功能是在 `+` 按钮里面打开的。
谢谢你的使用

**Comment by jaar23** [comment]
我会关了这个issue，如果还是fix不了再重开。

**Comment by 5kyfkr** [comment]
确实是token问题，感谢大佬
